### ISSUE TITLE
Submit to Main serverless plugins page

### ISSUE THREAD

**Issue by seriouscoderone** [economysizegeek/serverless-dir-config-plugin#1]
Going to try this out. Had to search hard for this.

Why is it not here? https://github.com/serverless/plugins

Do a PR.

**Comment by seriouscoderone** [comment]
Thought about this a lot. Seems like a plugin is not technically needed. If you leverage the Variables mechanisms instead it can be done this way. I think this approach would make it not so brittle (as you mention in your warning message)

```
service: team-demo-one

custom:
  functionFolders:
    - bots
    - api
  resourceFolders:
    - cloudformation
  matchFunctionPatterns:
    - '*.yml'
  matchResourcePatterns:
    - '*.yml'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:provider.stage}-${self:service}


functions:
  - ${file(includeFunctions.js)} # Auto-include functions recursively from functionFolders that matchFunctionPatterns
 
resources:
  # - ${file(includeResources.js)} # Auto-include resources recursively from resourceFolders that matchResourcePatterns
```

Where `includeFunctions.js` uses `const functionYml = serverless.utils.readFileSync(absolutePath)` to merge all the functions together
